blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/alefragnani/vscode-bookmarks/discussions?discussions_q=category%3AQ%26A
    about: Ask a question about Bookmarks